export const SET_COGNITOUSER = 'SET_COGNITOUSER';
export const SET_COGNITOUSERSESSION = 'SET_COGNITOUSERSESSION';

export const SET_LOCALE = 'SET_LOCALE'

export const SET_PROJECTDATA = 'SET_PROJECTDATA'
export const UPDATE_PROJECTATTRIBUTES = 'UPDATE_PROJECTATTRIBUTES'
export const RELEASE_PROJECTDATA = 'RELEASE_PROJECTDATA'
export const ADD_BUILDING = 'ADD_BUILDING'
export const EDIT_BUILDING = 'EDIT_BUILDING'
export const DELETE_BUILDING = 'DELETE_BUILDING'
export const SET_BUILDING_REGENREPORT = 'SET_BUILDING_REGENREPORT'
export const ADD_PV_SPEC = 'ADD_PV_SPEC'
export const EDIT_PV_SPEC = 'EDIT_PV_SPEC'
export const DELETE_PV_SPEC = 'DELETE_PV_SPEC'
export const ADD_INVERTER_SPEC = 'ADD_INVERTER_SPEC'
export const EDIT_INVERTER_SPEC = 'EDIT_INVERTER_SPEC'
export const DELETE_INVERTER_SPEC = 'DELETE_INVERTER_SPEC'

export const SET_PV_DATA = 'SET_PV_DATA'
export const SET_OFFICIAL_PV_DATA = 'SET_OFFICIAL_PV_DATA'

export const SET_INVERTER_DATA = 'SET_INVERTER_DATA'
export const SET_OFFICIAL_INVERTER_DATA = 'SET_OFFICIAL_INVERTER_DATA'

export const SET_REPORTDATA = 'SET_REPORTDATA'
export const UPDATE_REPORTATTRIBUTES = 'UPDATE_REPORTATTRIBUTES'
export const RELEASE_REPORTDATA = 'RELEASE_REPORTDATA'
export const DELETE_REPORTDATA = 'DELETE_REPORTDATA'

export const SET_MAP_KEY = 'SET_MAP_KEY'
export const SET_VIEWER = 'SET_VIEWER'
export const ENABLE_ROTATION = 'ENABLE_ROTATION'
export const DISABLE_ROTATION = 'DISABLE_ROTATION'
export const SELECT_MAP = 'SELECT_MAP'

export const DRAWING_STATUS_IDLE = 'DRAWING_STATUS_IDLE'
export const DRAWING_STATUS_POINT = 'DRAWING_STATUS_POINT'
export const DRAWING_STATUS_FOUNDLINE = 'DRAWING_STATUS_FOUNDLINE'

export const SET_PICKED_OBJECT = 'SET_PICKED_OBJECT'
export const RELEASE_PICKED_OBJECT = 'RELEASE_PICKED_OBJECT'
export const SET_HOVER_OBJECT = 'SET_HOVER_OBJECT'
export const RELEASE_HOVER_OBJECT = 'RELEASE_HOVER_OBJECT'


export const POINT_ADD = 'POINT_ADD'
export const POINT_MOVE_HORI = 'POINT_MOVE_HORI'
export const POINT_MOVE_VERTI = 'POINT_MOVE_VERTI'
