export const SET_COGNITOUSER = 'SET_COGNITOUSER';
export const SET_COGNITOUSERSESSION = 'SET_COGNITOUSERSESSION';

export const SET_LOCALE = 'SET_LOCALE'

export const SET_PROJECTDATA = 'SET_PROJECTDATA'
export const UPDATE_PROJECTATTRIBUTES = 'UPDATE_PROJECTATTRIBUTES'
export const RELEASE_PROJECTDATA = 'RELEASE_PROJECTDATA'
export const ADD_BUILDING = 'ADD_BUILDING'
export const EDIT_BUILDING = 'EDIT_BUILDING'
export const DELETE_BUILDING = 'DELETE_BUILDING'
export const SET_BUILDING_REGENREPORT = 'SET_BUILDING_REGENREPORT'
export const ADD_PV_SPEC = 'ADD_PV_SPEC'
export const EDIT_PV_SPEC = 'EDIT_PV_SPEC'
export const DELETE_PV_SPEC = 'DELETE_PV_SPEC'
export const ADD_INVERTER_SPEC = 'ADD_INVERTER_SPEC'
export const EDIT_INVERTER_SPEC = 'EDIT_INVERTER_SPEC'
export const DELETE_INVERTER_SPEC = 'DELETE_INVERTER_SPEC'

export const SET_PV_DATA = 'SET_PV_DATA'
export const SET_OFFICIAL_PV_DATA = 'SET_OFFICIAL_PV_DATA'

export const SET_INVERTER_DATA = 'SET_INVERTER_DATA'
export const SET_OFFICIAL_INVERTER_DATA = 'SET_OFFICIAL_INVERTER_DATA'

export const SET_REPORTDATA = 'SET_REPORTDATA'
export const UPDATE_REPORTATTRIBUTES = 'UPDATE_REPORTATTRIBUTES'
export const RELEASE_REPORTDATA = 'RELEASE_REPORTDATA'
export const DELETE_REPORTDATA = 'DELETE_REPORTDATA'

export const SET_PV_DIST = 'SET_PV_DIST'
export const SET_INVERTER_WIDTH = 'SET_INVERTER_WIDTH'
export const SET_INVERTER_DATA_SLD = 'SET_INVERTER_DATA_SLD'
export const SET_INTERCONNECT_DATA = 'SET_INTERCONNECT_DATA'
export const SET_SIZE = 'SET_SIZE'
export const SET_SERVER_PANEL = 'SET_SERVER_PANEL'
export const SET_METER = 'SET_METER'
export const SET_GRID = 'SET_GRID'